---
apiVersion: max.panw/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  name: max
  namespace: {{ .Values.namespace }}
spec:
  image: {{ .Values.sb_image }}
  maxReplicas: {{ .Values.sb_replicas }}
  env:
  - name: _STORYBUILDER_PARTITION_CONSUMER_ID
  - name: AIRFLOW_PROMETHEUS_DATABASE_PORT
    value: {{ include "airflow.database.port" . }}
  - name: AIRFLOW_PROMETHEUS_DATABASE_USER
    value: {{ include "airflow.database.user" . }}
  - name: AIRFLOW_PROMETHEUS_DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ include "airflow.postgresql.secretName" . }}
        key: {{ include "airflow.database.existingsecret.key" . }}
        url: "${DOLLAR}APOLLO2_HOSTNAME_EUROPE"
